[params]
    comments = false
    math = false

    ampModules = ["amp-analytics", "amp-sidebar", "amp-form","amp-iframe"]
    htmlModules = ["google-analytics", "disqus", "mathjax"]
    navbarLinkName = "link"
    navbarMenuName = "main"
    shareMenuName = "share"
