[params]
    comments = false
    math = false

    ampModules = ["amp-sidebar", "amp-analytics", "amp-iframe"]
    htmlModules = ["google-analytics", "disqus", "mathjax"]
    navbarMenuName = "main"
