[params]
    comments = false
    math = false
    modules = ["google-analytics", "disqus", "mathjax"]

[params.amp]
    modules = ["amp-analytics", "amp-iframe"]

[params.options]
    navbarMenuName = "main"
