name = "0x148"
license = "MIT"
licenselink = "https://github.com/progamesigner/hugo-theme-0x148/blob/master/LICENSE"
description = "A theme for Hugo with customizations."
homepage = "https://theme.0x148.com"
tags = [
    "AMP",
    "blog",
    "disqus",
    "google-analytics",
    "multilingual",
    "responsive"
]
features = [
    "analytics",
    "breadcrumbs",
    "comments",
    "disqus",
    "multi-author",
    "multilingual",
    "opengraph",
    "pagination",
    "responsive",
    "accessibility",
    "shortcodes",
    "single-column",
    "social-menu",
    "syntax-highlighting",
    "table-of-contents"
]
min_version = 0.55

[author]
    name = "Yang Sheng Han"
    homepage = "https://progamesigner.com"
