[[link]]
    title = "網站"
    name = "theme"
    url = "https://theme.0x148.com"
    weight = 0

[[link]]
    title = "GitHub"
    name = "github"
    url = "https://github.com/progamesigner/hugo-theme-0x148"
    weight = 10

[[share]]
    title = "分享到 Facebook"
    name = "facebook"
    url = "https://www.facebook.com/sharer.php?u={url}"
    weight = 10

[[share]]
    title = "轉推到 Twitter"
    name = "twitter"
    url = "https://twitter.com/intent/tweet?url={url}&text={title}"
    weight = 20

[[share]]
    title = "新增到 Trello 卡片"
    name = "trello"
    url = "https://trello.com/add-card?source={base}&url={url}&name={title}&desc={description}"
    weight = 30

[[share]]
    title = "儲存到 Pocket"
    name = "pocket"
    url = "https://getpocket.com/edit?url={url}"
    weight = 40

[[share]]
    title = "用 Email 分享"
    name = "email"
    url = "mailto:?subject={title}&body={url}"
    weight = 50
