[[link]]
    title = "Website"
    name = "theme"
    url = "https://theme.0x148.com"
    weight = 0

[[link]]
    title = "GitHub"
    name = "github"
    url = "https://github.com/progamesigner/hugo-theme-0x148"
    weight = 10

[[share]]
    title = "Share with Facebook"
    name = "facebook"
    url = "https://www.facebook.com/sharer.php?u={url}"
    weight = 10

[[share]]
    title = "Tweet to Twitter"
    name = "twitter"
    url = "https://twitter.com/intent/tweet?url={url}&text={title}"
    weight = 20

[[share]]
    title = "Add to Trello card"
    name = "trello"
    url = "https://trello.com/add-card?source={base}&url={url}&name={title}&desc={description}"
    weight = 30

[[share]]
    title = "Save to Pocket"
    name = "pocket"
    url = "https://getpocket.com/edit?url={url}"
    weight = 40

[[share]]
    title = "Share with Email"
    name = "email"
    url = "mailto:?subject={title}&body={url}"
    weight = 50
