baseURL = "https://example.com"
title = "Hugo 0x148 Theme Example"
description = "A theme for Hugo with customizations."

relativeURLs = true
paginate = 5

[author]
    name = "Your Name Here"
    email = "contact@example.com"
    url = "https://example.com"

[params]
    math = true
    share = true

    htmlModules = [
        "katex",
        "katex-auto-render",
        "katex-copy-tex"
    ]

[[menu.link]]
    title = "GitHub"
    name = "theme"
    url = "https://github.com/progamesigner/hugo-theme-0x148"

[[menu.share]]
    title = "Share with Facebook"
    name = "facebook"
    url = "https://www.facebook.com/sharer.php?u={url}"
    weight = 10

[[menu.share]]
    title = "Share with Twitter"
    name = "twitter"
    url = "https://twitter.com/intent/tweet?url={url}&text={title}"
    weight = 20

[[menu.share]]
    title = "Share with Email"
    name = "email"
    url = "mailto:?subject={title}&body={url}"
    weight = 30
