<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet
    version="2.0"
    xmlns:html="http://www.w3.org/TR/REC-html40"
    xmlns:sitemap="http://www.sitemaps.org/schemas/sitemap/0.9"
    xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
>
    <xsl:output method="html" version="1.0" encoding="UTF-8" indent="yes" />

    <xsl:template match="/">
        <html xmlns="http://www.w3.org/1999/xhtml">
            <head>
                <title>{{ .Site.Title }} Sitemap</title>
                <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
                <style type="text/css">
                    body {
                        color: #000000;
                        font-family: sans-serif;
                        font-size: 16px;
                        margin: 0 auto;
                        max-width: 1280px;
                        padding: 2% 5%;
                    }

                    a {
                        color: #114488;
                        font-weight: bold;
                        text-decoration: none;
                    }

                    a:hover {
                        text-decoration: underline;
                    }

                    .introduction {
                        line-height: 1.2em;
                        margin: 24px 4px;
                    }

                    .content {
                        margin: 0 4px;
                    }

                    .footer {
                        line-height: 1.2em;
                        margin: 24px 4px;
                        text-align: center;
                    }

                    table {
                        border: none;
                        border-collapse: collapse;
                        width: 100%;
                    }

                    th {
                        border-bottom: 1px solid #7d878a;
                        cursor: pointer;
                        text-align: left;
                        padding-right: 24px;
                    }

                    td {
                        padding: 8px 4px;
                    }

                    tr:nth-child(odd) td {
                        background-color: rgba(0, 0, 0, 0.04);
                    }

                    tr:hover td {
                        background-color: rgba(11, 44, 88, 0.08);
                    }
                </style>
            </head>

            <body>
                <h1>{{ .Site.Title }} Sitemap</h1>
                <div class="introduction">
                    <p>
                        This is a sitemap generated by <a href="https://gohugo.io">Hugo</a> {{ hugo.Version }} to allow search engines to discover content.
                    </p>
                </div>
                <div class="content">
                    <table cellpadding="5">
                        <tr style="border-bottom:1px black solid;">
                            <th>URL (<xsl:value-of select="count(sitemap:urlset/sitemap:url)" /> total)</th>
                            <th title="Priority">Priority</th>
                            <th title="Change Frequency">Change Frequency</th>
                            <th title="Last Modified (GMT)">Last Modified (GMT)</th>
                        </tr>
                        <xsl:variable name="lower" select="'abcdefghijklmnopqrstuvwxyz'" />
                        <xsl:variable name="upper" select="'ABCDEFGHIJKLMNOPQRSTUVWXYZ'" />
                        <xsl:for-each select="sitemap:urlset/sitemap:url">
                            <tr>
                                <td>
                                    <xsl:variable name="itemURL">
                                        <xsl:value-of select="sitemap:loc" />
                                    </xsl:variable>
                                    <a href="{$itemURL}">
                                        <xsl:value-of select="sitemap:loc" />
                                    </a>
                                </td>
                                <td>
                                    <xsl:value-of select="concat(sitemap:priority * 100, '%')" />
                                </td>
                                <td>
                                    <xsl:value-of select="concat(translate(substring(sitemap:changefreq, 1, 1), concat($lower, $upper), concat($upper, $lower)), substring(sitemap:changefreq, 2))" />
                                </td>
                                <td>
                                    <xsl:value-of select="concat(substring(sitemap:lastmod, 0, 11), concat(' ', substring(sitemap:lastmod, 12, 5)))" />
                                </td>
                            </tr>
                        </xsl:for-each>
                    </table>
                </div>
                {{ with .Site.Copyright }}
                    <div class="footer">
                        <p>{{ . | markdownify }}</p>
                    </div>
                {{ end }}
            </body>
        </html>
    </xsl:template>
</xsl:stylesheet>
