baseURL = "https://theme.0x148.com"
defaultContentLanguage = "en-us"
hasCJKLanguage = true
relativeURLs = true
paginate = 10

copyright = "Copyright (c) progamesigner."
enableRobotsTXT = true

pygmentsOptions = "linenos=table"
pygmentsUseClasses = true

[author]
    name = "Yang Sheng Han"
    email = "progamesigner@outlook.com"
    url = "https://progamesigner.com"

[params]
    comments = true
    toc = true

    mainSections = ["posts"]

    htmlModules = [
        "disqus",
        "google-analytics",
        "katex",
        "katex-auto-render",
        "katex-copy-tex"
    ]

[privacy]
[privacy.googleAnalytics]
    anonymizeIP = true
    respectDoNotTrack = true

[taxonomies]
    category = "categories"
    series = "series"
    tag = "tags"
